# Generated by Django 6.0.2 on 2026-03-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
